(function(g){var window=this;'use strict';var th=function(R){R.isActive()||R.start()},aY=function(R){var H={languageCode:R.languageCode,
languageName:R.languageName,displayName:g.tm(R),kind:R.kind,name:R.name,id:R.id,is_servable:R.V,is_default:R.isDefault,is_translateable:R.isTranslateable,vss_id:R.vssId};R.xtags&&(H.xtags=R.xtags);R.captionId&&(H.captionId=R.captionId);R.translationLanguage&&(H.translationLanguage=R.translationLanguage);return H},q5J=function(R,H){var h=new g.vM;
h.languageCode=R.languageCode;h.languageName=R.languageName;h.name=R.name;h.displayName=R.displayName;h.kind=R.kind;h.isDefault=!1;h.V=R.V;h.isTranslateable=R.isTranslateable;h.vssId=R.vssId;h.url=R.url;h.translationLanguage=H;R.xtags&&(h.xtags=R.xtags);R.captionId&&(h.captionId=R.captionId);return h},MW=function(R,H){return H?R.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Ljp=function(R){return g.TG(R)||R.G("web_enable_caption_language_preference_stickiness")},Wj4=async function(R,H){R=
R+"|"+H;
H=await g.C8();if(!H)throw g.lD("gct");return(await g.DE(H)).get("captions",R)},xba=function(R,H,h){Wj4(R,H).then(V=>{V&&h(V.trackData,new g.vM(V.metadata))})},gn=function(R){if(!BpC.test(R))throw Error("'"+R+"' is not a valid hex color");
R.length==4&&(R=R.replace(ibp,"#$1$1$2$2$3$3"));R=R.toLowerCase();R=parseInt(R.slice(1),16);return[R>>16,R>>8&255,R&255]},Uby=function(){var R={},H="suggest_correction"in g.ZM?g.ZM.suggest_correction:"Edit caption";
H=H||"";for(let h in R){let V=()=>String(R[h]);
H=H.replace(new RegExp("\\$\\{"+h+"\\}","gi"),V);H=H.replace(new RegExp("\\$"+h,"gi"),V)}return H},Fq=function(){return g.f3("yt-player-caption-display-settings")},vMy=function(R,H){g.qv(H,h=>R.equals(h))||H.push(R)},Q8=function(R,H){switch(H.kind){case "asr":vMy(H,R.L);
break;default:vMy(H,R.A)}},fMJ=async function(R,H,h){R.A=g.Ab(H,h)},yLJ=function(R,H){var h=g.VP(R.segments,H);
h>=0||h<0&&(-h-1)%2===1||(h=-h-1,h>0&&H-R.segments[h-1]===1&&h<R.segments.length&&R.segments[h]-H===1?(g.B$(R.segments,h),g.B$(R.segments,h-1)):h>0&&H-R.segments[h-1]===1?R.segments[h-1]=H:h<R.segments.length&&R.segments[h]-H===1?R.segments[h]=H:(g.Ru(R.segments,h,0,H),g.Ru(R.segments,h+1,0,H)))},Roy=function(R){return R.V&&R.V.Y?R.V.Y+R.player.I3()<R.player.getCurrentTime():!1},Hyp=function(R,H){if(R.policy.C6&&R.player.jf()){var h=g.o6(H,R.policy,{});
h.set("pot",R.player.jf());h=h.V9()}else h=g.o6(H,R.policy,{}).V9();var V={format:"RAW",withCredentials:!0};if(R.policy.rg){V.method="POST";let k=H.Y;k&&Object.keys(k).length>0?V.postBody=g.pc(k,g.Ox):V.postBody=(0,g.Ia)([120,0])}R.S&&(V.responseType="arraybuffer");var S=++R.Pd,r=(0,g.W)();R.A=g.Jb(h,V,3,100,-1,k=>{k.errorCode==="net.timeout"&&R.player.B("capnt",{rn:S++})}).then(k=>{if(R.policy.q8&&S%100===1){var u=(0,g.W)();
R.player.B("caprsp",{rn:S,ms:u-r,kb:(k.xhr.responseText.length/1024).toFixed()})}a:{k=k.xhr;R.YJ();if(R.L){var b=!(R.S?k.response:k.responseText)||k.status>=400;if(u=g.co(k)){k=g.o6(R.L,R.policy,{});R.L.TJ(k,u);Hyp(R,R.L);break a}b?R.player.B("capfail",{status:k.status}):(g.iO("fcb_r",(0,g.W)(),R.player.getVideoData()?.C||""),u=R.L.K2[0],b=u.Fu,R.N!=null&&R.X!==b&&(R.S?R.N(k.response,(u.startTime+R.player.I3())*1E3):R.N(k.responseText,(u.startTime+R.player.I3())*1E3),R.X=b))}R.L=null;R.A=null}}).kR(k=>
{R.L=null;
R.A=null;R.player.B("capfail",{rn:S,status:k.xhr?.status})});
R.L=H;yLJ(R.Y,R.L.K2[0].Fu)},hor=function(R,H){return H!=null&&H in R.A.V?R.A.V[H]:null},VjC=function(R,H,h){var V=[];
for(let S in R.A.V){if(!R.A.V.hasOwnProperty(S))continue;let r=R.A.V[S];if(g.DI(r,h||null)){let k=r.info.captionTrack;k&&k.languageCode===H&&V.push(r)}}return V.length?V[0]:null},rCy=function(R,H){var h=[];
for(let S in R.A.V){if(!R.A.V.hasOwnProperty(S))continue;var V=R.A.V[S];if(g.DI(V,H||null)){let r=V.info.id,k=r,u=`.${r}`,b="",T="";if(V=V.info.captionTrack)r=V.languageCode,k=V.displayName,u=V.vssId,b=V.kind,T=V.id;else{{V=r;let c=g.RsS.get(V);c==null&&(c=Sg9[V]||Sg9[V.replace(/-/g,"_")],g.RsS.set(V,c));V=c}k=V||k}h.push(new g.vM({id:S,languageCode:r,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:u,kind:b,captionId:T}))}}return h},NW=function(R){if(typeof DOMParser!="undefined")return g.px(new DOMParser,
g.Wf(R),"application/xml");
throw Error("Your browser does not support loading xml documents");},kHQ=function(R,H,h,V){var S=H/360*16;
H>=R&&(R=640,V>h*1.3&&(R=480),S=h/R*16);return S},uNr=function(R){var H=1+.25*(R.fontSizeIncrement||0);
if(R.offset===0||R.offset===2)H*=.8;return H},by4=function(R,H){var h="vertical-rl";
R.V.pL===1&&(h="vertical-lr");g.kO&&(h=h==="vertical-lr"?"tb-lr":"tb-rl");g.dX(H,"-o-writing-mode",h);g.dX(H,"-webkit-writing-mode",h);g.dX(H,"writing-mode",h);g.dX(H,"text-orientation","upright");g.Tn(H,"ytp-vertical-caption");R.L.params.qd===3&&(g.dX(H,"text-orientation",""),g.dX(H,"transform","rotate(180deg)"))},TRC=function(R,H){var h={},V=H.background?H.background:R.V.Ym.background;
if(H.backgroundOpacity!=null||H.background){var S=H.backgroundOpacity!=null?H.backgroundOpacity:R.V.Ym.backgroundOpacity;V=gn(V);h.background="rgba("+V[0]+","+V[1]+","+V[2]+","+S+")";R.Dq&&(h["box-decoration-break"]="clone",h["border-radius"]=`${R.Uh*.375}px`)}if(H.fontSizeIncrement!=null||H.offset!=null)h["font-size"]=`${R.kJ*uNr(H)}px`;V=1;S=H.color||R.V.Ym.color;if(H.color||H.textOpacity!=null)S=gn(S),V=H.textOpacity==null?R.V.Ym.textOpacity:H.textOpacity,S="rgba("+S[0]+","+S[1]+","+S[2]+","+V+
")",h.color=S,h.fill=S;var r=H.charEdgeStyle;r===0&&(r=void 0);if(r){S=`rgba(34, 34, 34, ${V})`;let b=`rgba(204, 204, 204, ${V})`;H.z4&&(b=S=H.z4);let T=R.kJ/16/2,c=Math.max(T,1);var k=Math.max(2*T,1),u=Math.max(3*T,1);let e=Math.max(5*T,1);V=[];switch(r){case 4:for(;u<=e;u+=T)V.push(`${k}px ${k}px ${u}px ${S}`);break;case 1:k=window.devicePixelRatio>=2?.5:1;for(r=c;r<=u;r+=k)V.push(`${r}px ${r}px ${S}`);break;case 2:V.push(`${c}px ${c}px ${b}`);V.push(`-${c}px -${c}px ${S}`);break;case 3:for(u=0;u<
5;u++)V.push(`0 0 ${k}px ${S}`)}h["text-shadow"]=V.join(", ")}S="";switch(H.fontFamily){case 1:S='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:S='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:S='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:S='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:S='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:S=g.rg()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:S='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}S&&(h["font-family"]=S);S=H.offset;S==null&&(S=R.V.Ym.offset);switch(S){case 0:h["vertical-align"]="sub";break;case 2:h["vertical-align"]="super"}H.fontFamily===7&&(h["font-variant"]="small-caps");H.bold&&(h["font-weight"]="bold");H.italic&&(h["font-style"]="italic");H.underline&&
(h["text-decoration"]="underline");H.OQ&&(h.visibility="hidden");H.I7===1&&R.S&&(h["text-combine-upright"]="all",h["text-orientation"]="mixed",S=g.mm||g.XP,R.L.params.qd===3?h.transform=S?"rotate(90deg)":"rotate(180deg)":S&&(h.transform="rotate(-90deg)"));if(H.textEmphasis===1||H.textEmphasis===2||H.textEmphasis===3||H.textEmphasis===4||H.textEmphasis===5)if(g.mm)h["font-weight"]="bold";else switch(h["text-emphasis-style"]="filled circle",h["text-emphasis-color"]="currentcolor",h["webkit-text-emphasis"]=
"filled circle",H.textEmphasis){case 4:case 3:h["text-emphasis-position"]="under left";h["webkit-text-emphasis-position"]="under left";break;case 5:case 2:h["text-emphasis-position"]="over right",h["webkit-text-emphasis-position"]="over right"}return h},s4=function(R){R=R.split("px");
return R.length>0?(R=Number(R[0]))?R:0:0},Dxy=function(R,H,h){R.hL=R.hL||!!h;
var V={};Object.assign(V,R.V.Ym);Object.assign(V,h||H.V);Object.assign(V,R.Kf.Ym);(h=!R.C)&&cCy(R);var S=R.Nt&&R.Eh&&g.I_(V,R.Eh)?R.Nt:eoJ(R,V),r=typeof H.text==="string",k=r?H.text.split("\n"):[H.text];for(let b=0;b<k.length;b++){var u=b>0||!H.append;let T=k[b];u&&!h?(cCy(R),S=eoJ(R,V)):u&&h&&(h=!1);T&&(S.appendChild(r?g.CK(T):T),r||T.tagName!=="RUBY"||T.childElementCount!==4||g.mm||!g.nA(T.children[2],"text-emphasis")||(u=R.S?"padding-right":"padding-top",g.nA(T.children[2],"text-emphasis-position")&&
(u=R.S?"padding-left":"padding-bottom"),g.Du?g.dX(S,u,"1em"):g.dX(S,u,"0.5em")))}R.Eh=V;R.Nt=S;R.N.push(H)},cCy=function(R){R.C=g.GE("SPAN");
g.dX(R.C,{display:"block"});g.Tn(R.C,"caption-visual-line");R.X.appendChild(R.C)},eoJ=function(R,H){var h=g.GE("SPAN");
g.dX(h,{display:"inline-block","white-space":"pre-wrap"});g.dX(h,TRC(R,H));h.classList.add("ytp-caption-segment");R.C.appendChild(h);h.previousElementSibling&&(g.dX(h.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.dX(h,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return h},$xW=function(R,H,h){if(R===255&&H===255||!R&&!H)return{kB:R,
QN:H,result:0};R=pUa[R];H=pUa[H];if(R&128){var V;if(V=!(H&128))V=H,V=h.AP()&&h.QN===V;if(V)return{kB:R,QN:H,result:1}}else if(H&128&&1<=R&&R<=31)return{kB:R,QN:H,result:2};return{kB:R,QN:H,result:3}},Yga=function(R,H,h,V){H===255&&h===255||!H&&!h?(++R.L===45&&R.reset(),R.Y.A.clear(),R.S.A.clear()):(R.L=0,mxa(R.Y,H,h,V))},jkW=function(R,H){R.V.sort((h,V)=>{var S=h.time-V.time;
return S===0?h.order-V.order:S});
for(let h of R.V)R.time=h.time,h.type===0?Yga(R,h.AB,h.yk,H):h.type===1&&R.A&496&&mxa(R.S,h.AB,h.yk,H);R.V.length=0},KfW=function(R,H){switch(R){case 0:return GHC[(H&127)-32];
case 1:return C_J[H&15];case 2:return zop[H&31];case 3:return EFr[H&31]}return 0},PG=function(R,H){if(R.style.type===3){var h=0,V=0,S=R.S.time+0,r="",k="",u=S;
for(var b=1;b<=15;++b){var T=!1;for(var c=V?V:1;c<=32;++c){var e=R.L[b][c];if(e.V!==0){h===0&&(h=b,V=c);T=String.fromCharCode(e.V);var D=e.timestamp;D<S&&(S=D);e.timestamp=u;k&&(r+=k,k="");r+=T;T=!0}if((e.V===0||c===32)&&T){k="\n";break}else if(V&&!T)break}if(h&&!T)break}r&&H.Y(h,V,S,u,r)}else for(V=h=0,r=S=R.S.time+0,k=1;k<=15;++k)for(u="",b=1;b<=32;++b)if(c=R.L[k][b],e=c.V,e!==0&&(h===0&&(h=k,V=b),T=String.fromCharCode(e),D=c.timestamp,D<=S&&(S=D),u+=T,c.reset()),b===32||e===0)u&&H.Y(h,V,S,r,u),
S=r,u="",V=h=0},Xq=function(R){return R.L[R.row][R.A]},Ah=function(R,H,h){H>=2&&R.A>1&&(--R.A,Xq(R).V=0);
var V=Xq(R);V.timestamp=R.S.time+0;V.V=KfW(H,h);R.A<32&&R.A++},tjp=function(R,H,h,V){for(let k=0;k<V;k++)for(let u=0;u<=32;u++){var S=R.L[H+k][u],r=R.L[h+k][u];
S.V=r.V;S.timestamp=r.timestamp}},ZS=function(R,H,h){for(let V=0;V<h;V++)for(let S=0;S<=32;S++)R.L[H+V][S].reset()},l7=function(R){R.row=R.V>0?R.V:1;
R.A=1;ZS(R,0,15)},aRy=function(R){R.style.set(1);
R.V=R.Y;R.V.V=0;R.V.style=R.style;R.L.mode=1<<R.V.Y},wn=function(R,H,h){var V=R.A,S=!1;
switch(R.style.get()){case 4:case 1:case 2:R.style.get()===4&&V.V>0||(PG(V,h),l7(R.A),l7(R.Y),V.row=15,V.V=H,S=!0)}R.style.set(3);R.V=V;R.V.style=R.style;R.L.mode=1<<V.Y;S?V.A=1:V.V!==H&&(V.V>H?(PG(V,h),ZS(V,V.row-V.V,H)):V.row<H&&(H=V.V),V.V=H)},Mj4=function(R){R.style.set(4);
R.V=R.text;R.V.style=R.style;R.L.mode=1<<R.V.Y},mxa=function(R,H,h,V){R.A.update();
H=$xW(H,h,R.A);switch(H.result){case 0:return;case 1:case 2:return}var S=H.kB;H=H.QN;if(32<=S||!S)R.V.mode&R.V.A&&(h=S,h&128&&(h=127),H&128&&(H=127),R=R.Y.V,h&96&&Ah(R,0,h),H&96&&Ah(R,0,H),h!==0&&H!==0&&R.style.type===3&&PG(R,V));else if(S&16)a:if(!R.A.matches(S,H)&&(h=R.A,h.kB=S,h.QN=H,h.state=2,h=S&8?R.X:R.L,R.Y=h,R.V.mode=1<<(R.S<<2)+(h.S<<1)+(h.style.type===4?1:0),(R.V.mode|1<<(R.S<<2)+(h.S<<1)+(h.style.type!==4?1:0))&R.V.A))if(H&64){V=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(S&7)<<1|H>>5&1];
R=H&16?((H&14)>>1)*4:0;H=h.V;switch(h.style.get()){case 4:V=H.row;break;case 3:if(V!==H.row){if(V<H.V&&(V=H.V,V===H.row))break;var r=1+H.row-H.V;let k=1+V-H.V;tjp(H,k,r,H.V);h=r;S=H.V;k<r?(r=k+S-r,r>0&&(h+=r,S-=r)):(r=r+S-k,r>0&&(S-=r));ZS(H,h,S)}}H.row=V;H.A=R+1}else switch(S&7){case 1:switch(H&112){case 32:Ah(h.V,0,32);break a;case 48:H===57?(V=h.V,Xq(V).V=0,V.A<32&&V.A++):Ah(h.V,1,H&15)}break;case 2:H&32&&Ah(h.V,2,H&31);break;case 3:H&32&&Ah(h.V,3,H&31);break;case 4:case 5:if(32<=H&&H<=47)switch(H){case 32:aRy(h);
break;case 33:V=h.V;V.A>1&&(--V.A,Xq(V).V=0);break;case 36:V=h.V;R=Xq(V);for(H=0;H<=15;H++)for(h=0;h<=32;h++)if(V.L[H][h]===R){for(;h<=32;h++)V.L[H][h].reset();break}break;case 37:wn(h,2,V);break;case 38:wn(h,3,V);break;case 39:wn(h,4,V);break;case 40:Ah(h.V,0,32);break;case 41:V=h;V.style.set(2);V.V=V.A;V.V.V=0;V.V.style=V.style;V.L.mode=1<<V.V.Y;break;case 42:V=h;R=V.text;R.V=15;R.style.set(4);l7(R);Mj4(V);break;case 43:Mj4(h);break;case 44:R=h;H=R.A;switch(R.style.get()){case 1:case 2:case 3:PG(H,
V)}ZS(H,0,15);break;case 45:b:{H=h;R=H.V;switch(H.style.get()){default:case 2:case 1:break b;case 4:if(R.row<15){++R.row;R.A=1;break b}break;case 3:}R.V<2&&(R.V=2,R.row<R.V&&(R.row=R.V));H=R.row-R.V+1;PG(R,V);tjp(R,H,H+1,R.V-1);ZS(R,R.row,1)}break;case 46:ZS(h.Y,0,15);break;case 47:R=h,PG(R.A,V),R.Y.updateTime(R.L.time+0),V=R.Y,R.Y=R.A,R.A=V,aRy(R)}break;case 7:switch(H){case 33:case 34:case 35:V=h.V,(V.A+=H&3)>32&&(V.A=32)}}},FfG=function(R,H,h,V,S,r,k){var u=r[0],b=k[u.getAttribute("p")];
if(b.IT===1){var T=r[1],c=r[2];r=r[3];u.getAttribute("t");T.getAttribute("t");c.getAttribute("t");r.getAttribute("t");u.getAttribute("p");T.getAttribute("p");r.getAttribute("p");k=k[c.getAttribute("p")];u=gFJ(u.textContent,T.textContent,c.textContent,r.textContent,k);return new O4(R,H,S,h,u,V,b)}switch(b.IT){case 9:case 10:b.textEmphasis=1;break;case 11:b.textEmphasis=2;break;case 12:b.textEmphasis=3;break;case 13:b.textEmphasis=4;break;case 14:b.textEmphasis=5}return new O4(R,H,S,h,u.textContent||
"",V,b)},gFJ=function(R,H,h,V,S){var r=g.rg(),k=r?g.GE("DIV"):g.GE("RUBY"),u=g.GE("SPAN");
u.textContent=R;k.appendChild(u);R=r?g.GE("DIV"):g.GE("RP");R.textContent=H;k.appendChild(R);H=r?g.GE("DIV"):g.GE("RT");H.textContent=h;k.appendChild(H);h=S.IT;if(h===10||h===11||h===12||h===13||h===14)if(g.dX(H,"text-emphasis-style","filled circle"),g.dX(H,"text-emphasis-color","currentcolor"),g.dX(H,"webkit-text-emphasis","filled circle"),S.IT===11||S.IT===13)g.dX(H,"webkit-text-emphasis-position","under left"),g.dX(H,"text-emphasis-position","under left");h=!0;if(S.IT===4||S.IT===7||S.IT===12||
S.IT===14)g.dX(k,"ruby-position","over"),g.dX(k,"-webkit-ruby-position","before");else if(S.IT===5||S.IT===6||S.IT===11||S.IT===13)g.dX(k,"ruby-position","under"),g.dX(k,"-webkit-ruby-position","after"),h=!1;S=r?g.GE("DIV"):g.GE("RP");S.textContent=V;k.appendChild(S);r&&(V=h,g.dX(k,{display:"inline-block",position:"relative"}),r=k.firstElementChild.nextElementSibling,g.dX(r,"display","none"),r=r.nextElementSibling,g.dX(r,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.dX(k.lastElementChild,"display","none"),V?(g.dX(k,"padding-top","0.6em"),g.dX(r,"top","0")):(g.dX(k,"padding-bottom","0.6em"),g.dX(r,"bottom","0")));return k},Qkr=function(R){var H="_"+dn++;
return new IY(0,0x8000000000000,0,H,R)},oY=function(R,H){R=R.getAttribute(H);
if(R!=null)return Number(R)},Jh=function(R,H){R=R.getAttribute(H);
if(R!=null)return R==="1"},nW=function(R,H){R=oY(R,H);
return R!==void 0?R:null},LW=function(R,H){R=R.getAttribute(H);
if(R!=null)return qW.test(R),R},NRJ=function(R,H){var h={},V=H.getAttribute("ws");
Object.assign(h,V?R.C[V]:R.Y);R=nW(H,"mh");R!=null&&(h.Oz=R);R=nW(H,"ju");R!=null&&(h.textAlign=R);R=nW(H,"pd");R!=null&&(h.qd=R);R=nW(H,"sd");R!=null&&(h.pL=R);R=LW(H,"wfc");R!=null&&(h.windowColor=R);H=oY(H,"wfo");H!==void 0&&(h.windowOpacity=H/255);return h},skj=function(R,H){var h={},V=H.getAttribute("wp");
V&&Object.assign(h,R.N[V]);R=nW(H,"ap");R!=null&&(h.Su=R);R=oY(H,"cc");R!=null&&(h.VN=R);R=oY(H,"ah");R!=null&&(h.FD=R);R=oY(H,"rc");R!=null&&(h.IY=R);H=oY(H,"av");H!=null&&(h.ER=H);return h},P_U=function(R,H,h,V){var S={};
Object.assign(S,skj(R,H));Object.assign(S,NRJ(R,H));V?g.I_(S,R.Y)?(V=R.S,S=R.Y):V="_"+dn++:V=H.getAttribute("id")||"_"+dn++;R=oY(H,"t")+h;H=oY(H,"d")||0x8000000000000;if(S.qd===2||S.qd===3)h=S.IY,S.IY=S.VN,S.VN=h;return new IY(R,H,0,V,S)},WG=function(R){R=g.Y6(Math.round(R),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-R.length)+R},XUy=function(R,H,h,V,S){V===0&&(V=0x8000000000000);
var r={};H.wpWinPosId&&Object.assign(r,R.Y.get(H.wpWinPosId));H.wsWinStyleId&&Object.assign(r,R.S.get(H.wsWinStyleId));R=H.rcRowCount;R!==void 0&&(r.IY=R);H=H.ccColCount;H!==void 0&&(r.VN=H);if(r.qd===2||r.qd===3)H=r.IY,r.IY=r.VN,r.VN=H;return new IY(h,V,0,S,r)},x8=function(R){var H=R.byteOffset;
R.byteOffset+=1;return R.V.getUint8(H)},BG=function(R){var H=R.byteOffset;
R.byteOffset+=4;return R.V.getUint32(H)},lRG=function(R){if(typeof R==="string")return!1;
R=new ACp(R,0);return Zyy(R)},Zyy=function(R){if(!(R.byteOffset<R.V.byteLength)||BG(R)!==1380139777)return!1;
R.version=x8(R);if(R.version>1)return!1;x8(R);x8(R);x8(R);return!0},wUW=function(R,H){if(!H)return"";
R.S&&R.L.params.pL!==1&&(H*=-1);return`translate${R.S?"X":"Y"}(${H}px)`},Oy4=function(R){R.rg=Array.from(R.element.getElementsByClassName("caption-visual-line"));
for(var H=R.L.params.IY,h=0,V=0,S=R.rg.length-1;h<H&&S>-1;){var r=R.rg[S];V+=R.S?r.offsetWidth:r.offsetHeight;h++;S--}R.Pd=V;H=Math;h=H.max;isNaN(R.SR)&&((V=R.V.VN)?(S=g.GE("SPAN"),g.aU(S,"\u2013".repeat(V)),g.dX(S,TRC(R,R.V.Ym)),R.X.appendChild(S),R.SR=S.offsetWidth,R.X.removeChild(S)):R.SR=0);V=R.X;R.Mt=h.call(H,R.SR,R.nf,(R.S?V.offsetHeight:V.offsetWidth)+1)},dx3=function(R,H){Oy4(R);
var h=R.rg.reduce((V,S)=>(R.S?S.offsetWidth:S.offsetHeight)+V,0);
h=R.Pd-h;if(h!==R.Oh){let V=h>0&&R.Oh===0,S=h<R.Oh;H||isNaN(h)||V||!S||(g.Tn(R.element,"ytp-rollup-mode"),R.Qs(R.element,"transitionend",R.Wd));g.dX(R.X,"transform",wUW(R,h));R.Oh=h}Oy4(R)},oF4=function(R,H,h,V){var {formatId:S,
Fu:r,startTimeMs:k,durationMs:u}=R.S(H),b={formatId:S,startTimeMs:k,durationMs:u,x8:r,w2:r},T=IRJ(R.bZ,b.startTimeMs),c=T>=0?R.bZ[T]:null,e=c?c.startTimeMs+c.durationMs:0,D=b.startTimeMs+b.durationMs;!c||b.startTimeMs-e>R.Y?R.bZ.splice(T+1,0,b):(c.durationMs=Math.max(e,D)-c.startTimeMs,c.w2=Math.max(c.w2,b.w2));V(R.bZ);V=g.rj(H);R=R.X;V=V.buffer.slice(V.byteOffset,V.byteLength+V.byteOffset);H=H.info.L;R.W?R.N==null?g.Hj(R.logger,350058965,"Null loaded track meta data at captions data received"):h.Ho(V,
R.N,H*1E3):g.Hj(R.logger,350058965,"Null Representation at captions data received")},qgj=function(R,H){R.A=(h,V)=>{if(R.j.U().experiments.dg("html5_sabr_live_support_subfragmented_captions"))(R.V?R.V=R.V.S(h):(R.V=h,JCW(R.V)),R.V)?h.info.S0&&(nFy(R.V),oF4(R,R.V,H,V),R.V=null):g.Hj(R.logger,350058965,"Empty slice");
else if(h.info.S0){var S=h;if(R.LW.length>0){for(S=R.LW.shift();R.LW.length>0;)S=S.S(R.LW.shift());S=S.S(h)}S?(JCW(S),nFy(S),oF4(R,S,H,V)):g.Hj(R.logger,350058965,"Empty slice")}else R.LW.push(h)};
R.j.addEventListener("sabrCaptionsDataLoaded",R.A)},IRJ=function(R,H){R=g.VP(R,{startTimeMs:H},(h,V)=>h.startTimeMs-V.startTimeMs);
return R>=0?R:-R-2},JCW=function(R){try{var H=g.T5(R)*1E3}catch(h){H=R.info.startTime*1E3}H<0&&(H=R.info.startTime*1E3);
R.info.startTime=H/1E3;R.info.L=H/1E3},nFy=function(R){try{var H=g.$Y(R)*1E3}catch(h){H=R.info.duration*1E3}H<0&&(H=R.info.duration*1E3);
R.info.duration=H/1E3;R.info.J=H/1E3},LfS=function(R,H){if(!g.lX(R)||R.V!=null&&g.eH(H,R.V)&&R.V.V.rawcc!=null)return!1;
H=!!R.V&&R.V.isManifestless&&Object.values(R.V.V).some(h=>g.DI(h,"386"));
R=!!R.V&&!R.V.isManifestless&&g.N8(R.V);return H||R},Wfy=function(R,H,h){var V=[];
for(let S in R.A.V){if(!R.A.V.hasOwnProperty(S))continue;let r=R.A.V[S];if(g.DI(r,h||null)){let k=r.info.captionTrack;k&&k.languageCode===H&&V.push(r)}}return V.length?V[0]:null},xxa=function(R,H){var h=[];
for(let S in R.A.V){if(!R.A.V.hasOwnProperty(S))continue;var V=R.A.V[S];if(g.DI(V,H||null)){let r=V.info.id,k=r,u=`.${r}`,b="",T="";if(V=V.info.captionTrack)r=V.languageCode,k=V.displayName,u=V.vssId,b=V.kind,T=V.id;h.push(new g.vM({id:S,languageCode:r,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:u,kind:b,captionId:T}))}}return h},iy3=function(R){var H=BR3.length;
if(R.byteLength<H)return!1;R=new Uint8Array(R,0,H);for(let h=0;h<H;h++)if(BR3[h]!==R[h])return!1;return!0},i7=function(R){R=R.split(":");
var H=0;for(let h of R)H=H*60+Number(h);return H*1E3},Uxa=function(R,H,h,V){V=Object.assign({Oz:0},V);
return new IY(R,H,h,"_"+dn++,V)},vFW=function(R,H,h,V,S,r,k,u,b){switch(k.tagName){case "b":u.bold=!0;
break;case "i":u.italic=!0;break;case "u":u.underline=!0}for(let c=0;c<k.childNodes.length;c++){var T=k.childNodes[c];if(T.nodeType===3)T=new O4(H,h,V,S.id,T.nodeValue,r||c>0,g.wk(u)?void 0:u),b.push(T),S.V.push(T);else{let e={};Object.assign(e,u);vFW(R,H,h,V,S,!0,T,e,b)}}},yCW=function(R,H,h){if(typeof H==="string"||lRG(H))return[{trackData:H,
aZ:h}];if(typeof H==="string"&&H.substring(0,6)==="WEBVTT"||typeof H!=="string"&&iy3(H))return[{trackData:H,aZ:h}];var V=new DataView(H);if(V.byteLength<=8||V.getUint32(4)!==1718909296)return[];var S=g.sX(V);if(R.XI&&S){var r=g.Do(S),k=g.pi(S);S=S.segmentNumber;r&&S&&R.XI.Mq(S,r,k)}R=g.Fl(V,1835295092);if(!R||!R.length||!R[0].size)return[];r=[];for(k=0;k<R.length;k++)S=R[k],S=new Uint8Array(H,S.dataOffset,S.size-(S.dataOffset-S.offset)),S=g.L_(S),r.push({trackData:S,aZ:h+k*1E3});fR9(V,r,h);return r=
r.filter(u=>!!u.trackData)},HsW=function(R,H,h){R.V||(R.V=new Rw3);
R=R.V.L(H,h);Math.random()<.01&&g.Bz(Error("Deprecated subtitles format in web player: WebVTT"));return R},fR9=function(R,H,h){var V=g.Ci(R,0,1836476516),S=9E4;
V&&(S=g.Ki(V)||9E4);V=0;var r=g.Fl(R,1836019558);for(let u=0;u<r.length;u++){var k=r[u];u<H.length&&(k=g.Ci(R,k.dataOffset,1953653094))&&(k=g.Ci(R,k.dataOffset,1952867444))&&(k=g.ML(k)/S*1E3,u===0&&(V=k),H[u].aZ=k-V+h||h*u*1E3)}},hwj=function(R){var H={};
if(R=g.aO(R))H.lang=R,g.H5S.test(R)&&(H.qd=1);return H},VvC=function(R){var H=!!R.j.Hg()?.SR();
return R.L==="HLS"&&H?!0:R.Eh&&H&&R.L!=="LIVE"&&R.L!=="SABR_LIVE"},U4=function(R,H,h=!1){var V=R.O.G("enable_player_captions_new_style_defaults")?StW:r2S,S=V.Ym;
R.S={};Object.assign(R.S,V);R.S.Ym={};Object.assign(R.S.Ym,S);R.X={Ym:{}};var r=H.backgroundOverride?R.X:R.S,k=H.background||S.background;qW.test(k);r.Ym.background=k;r=H.colorOverride?R.X:R.S;k=H.color||S.color;qW.test(k);r.Ym.color=k;r=H.windowColorOverride?R.X:R.S;k=H.windowColor||V.windowColor;qW.test(k);r.windowColor=k;r=H.backgroundOpacityOverride?R.X:R.S;k=H.backgroundOpacity;k==null&&(k=S.backgroundOpacity);r.Ym.backgroundOpacity=k;r=H.fontSizeIncrementOverride?R.X:R.S;k=H.fontSizeIncrement;
k==null&&(k=S.fontSizeIncrement);r.Ym.fontSizeIncrement=k;k=H.fontStyleOverride?R.X:R.S;r=H.fontStyle;r==null&&(r=S.bold&&S.italic?3:S.bold?1:S.italic?2:0);k=k.Ym;switch(r){case 1:k.bold=!0;delete k.italic;break;case 2:delete k.bold;k.italic=!0;break;case 3:k.bold=!0;k.italic=!0;break;default:delete k.bold,delete k.italic}r=H.textOpacityOverride?R.X:R.S;k=H.textOpacity;k==null&&(k=S.textOpacity);r.Ym.textOpacity=k;r=H.windowOpacityOverride?R.X:R.S;k=H.windowOpacity;k==null&&(k=V.windowOpacity);r.windowOpacity=
k;V=H.charEdgeStyleOverride?R.X:R.S;r=H.charEdgeStyle;r==null&&(r=S.charEdgeStyle);V.Ym.charEdgeStyle=r;V=H.fontFamilyOverride?R.X:R.S;r=H.fontFamily;r==null&&(r=S.fontFamily);V.Ym.fontFamily=r;R.loaded&&R.Uh();h&&g.vb("yt-player-caption-display-settings",H,2592E3)},vG=function(R,H,h){H&&!R.K?(H=Qkr({qd:0,
lang:"en"}),R.K=[H,new O4(H.start,H.end-H.start,0,H.id,h??"Captions look like this")],R.player.ey(R.K)):!H&&R.K&&(kUU(R,R.K),R.K=null)},uTU=function(R){if(!R.j.isInline())return g.f3("yt-player-sticky-caption")},fW=function(R){if(!R.O.G("web_watch_deprecate_always_show_captions_setting")){var H=void 0,h=g.nV().zp(65);
if(g.TG(R.O)&&h!=null){if(uTU(R)!=null)return!1;H=!h}return H}},bsC=function(R){if(R.O.BP===1||R.videoData.TX===1||g.aQ(R.videoData,"yt:cc")==="alwayson")return!0;
if(R.videoData.captionTracks.length)var H=R.getAudioTrack().A;if(R.O.G("enable_player_captions_persistence_state_machine")){var h=R.O.G("enable_player_captions_persistence_state_machine")?g.f3("yt-player-caption-persistence"):void 0;if(h!==void 0)return!!h}else if(R.O.BP===2){if(g.TG(R.O))h=uTU(R);else if(R.storage)try{h=R.storage.get("module-enabled")}catch(S){R.storage.remove("module-enabled")}else h=null;if(h!=null)return!!h}h=MW(R.player.getAudioTrack(),g.TG(R.O));var V=g.aQ(R.videoData,"yt:cc");
if(fW(R)===void 0){if(h==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return V?V==="on":!0;if(h==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return V==="on"}else return V==="on";return H==="ON"||g.aQ(R.videoData,"yt:cc")==="on"},y8=function(R,H=!1){if(R.A&&!H||!R.videoData.captionTracks.length)return!1;
R=R.getAudioTrack();return!!R.V||R.A==="FORCED_ON"},T0p=function(R){return R.O.G("html5_honor_caption_availabilities_in_audio_track")&&R.L!=="LIVE"&&R.L!=="SABR_LIVE"},c2p=function(R,H){if(R.A){var h=R.j.Hg().vg().textTracks,V=null;
R.L==="HLS"?V=R.A.getId():V=R.A.toString();for(let r=0;r<h.length;r++){var S=h[r];S.id===V&&(H?S.mode!=="showing"&&(S.mode="showing",S=R.A,R.hJ(S,!!S,RW(R)?"g":R.N?"m":"s")):S.mode==="showing"&&(S.mode="disabled"))}}},RW=function(R){var H=H9(R);
return!!H&&R.A===H},ewC=function(R,H){if(R.L==="HLS")return!1;
g.Xb(R.videoData)&&(H=!0);H||(H=R.L==="TTS"?!1:R.L==="INNERTUBE"?!1:!0);return H||R.O.G("web_watch_disable_account_level_captions_settings")&&g.TG(R.O)?!0:!!g.nV().zp(66)},H9=function(R){return R.C&&R.C.V},hT=function(R,H){if(!R.V)return null;
if(R.C&&R.C.Y)return R.C.Y;H=ewC(R,H);H=R.V.V.V(H);var h=null;if(Ljp(R.O)){var V=R.j.isInline()?void 0:g.f3("yt-player-caption-sticky-language");var S=[V,R.videoData.captionsLanguagePreference,R.O.captionsLanguagePreference,g.aQ(R.videoData,"yt:cc_default_lang")];let u=!1;for(let b=0;b<S.length;b++){let T=S[b];if(T){u=!0;for(var r=0;r<H.length;r++)if(g.aO(H[r])===T)return H[r];for(r=0;r<H.length;r++)if(g.aO(H[r]).split("-")[0]===T.split("-")[0])return H[r]}}if(u&&R.V&&(S=R.V.C,S.length))for(var k of S)if(k.languageCode===
V){h=k;break}}else for(k=[R.videoData.captionsLanguagePreference,R.O.captionsLanguagePreference,g.aQ(R.videoData,"yt:cc_default_lang")],V=0;V<k.length;V++)for(S=0;S<H.length;S++)if(g.aO(H[S])===k[V])return H[S];k=null;R.C&&R.C.L&&(k=R.C.L);k||(k=H.find(u=>u.isDefault)||null);
k||(k=H[0]||H9(R));k&&h&&g.aO(k).split("-")[0]!==h.languageCode.split("-")[0]&&(k=q5J(k,h));return k},uj=function(R,H,h){R.loaded&&R.unload();
h!=null&&(R.N=h,R.N&&(R.O.G("enable_player_captions_persistence_state_machine")?VO(R,!!H):g.TG(R.O)?Sq(R,!!H):r8(R,!!H)));H!==null||y8(R,!0)||R.hJ(H,!!H,R.N?"m":"s");R.A=H;y8(R)&&(R.A=H9(R));kz(R,R.A??void 0);R.load()},VO=function(R,H){R.O.G("enable_player_captions_persistence_state_machine")&&g.vb("yt-player-caption-persistence",H,3122064E3)},Sq=function(R,H){R.j.isInline()||g.vb("yt-player-sticky-caption",H,2592E3)},r8=function(R,H){if(R.storage)try{R.storage.set("module-enabled",H)}catch(h){}},
kz=function(R,H){R.O.G("html5_modify_caption_vss_logging")&&(R.videoData.Wh=H)},pRC=function(R,H){var h=R.Pd[H.id];
h&&h.L!==H&&(h.dispose(),delete R.Pd[H.id],h=null);h||(h=DUU(R,H))&&(R.Pd[H.id]=h)},$UW=function(R,H){var h=H.windowId;
R.RB[h]||(R.RB[h]=[]);R.RB[h].push(H)},DUU=function(R,H){var h=mUj(R);
if(!h)return null;var V=R.A?g.aO(R.A):null;V&&g.H5S.test(V)&&(H.params.qd=1);var S=R.bK.getPlayerSize();V=S.height*R.W.height;S=S.width*R.W.width;R.O.playerStyle!=="google-live"||R.S.isDefault||Object.assign(H.params,R.S);switch(H.params.Oz!=null?H.params.Oz:H.V.length>1?1:0){case 1:return new YtQ(H,R.S,R.X,h.width,h.height,S,V,R.O.experiments,R.kJ.bind(R),R.j);case 2:return new jEC(H,R.S,R.X,h.width,h.height,S,V,R.O.experiments,R.kJ.bind(R),R.j);default:return new bj(H,R.S,R.X,h.width,h.height,S,
V,R.O.experiments,R.kJ.bind(R),R.j)}},mUj=function(R){var H=R.bK.getVideoContentRect(!0).height,h=R.bK.getVideoContentRect(!0).width;
if(!H||!h)return null;H*=R.W.height;h*=R.W.width;return{width:h,height:H}},kUU=function(R,H){R.player.zD(H);
for(let h of H)g.iJ(R.rg,h);th(R.SR)},GUJ=function(R,H){if(!R.V)return{};
if(H){g.wk(H)||R.TY(H.vss_id,"m");if(R.Y&&R.L!=="HLS"||!g.KC(H))return;if(g.wk(H)){uj(R,null,!0);return}let V;var h=R.V.V.V(!0);for(let S=0;S<h.length;S++){let r=h[S];r.languageCode!==H.languageCode||V&&(r.languageName!==H.languageName||(r.captionId||"")!==(H.captionId||"")||g.tm(r)!==H.displayName)||(V=H.translationLanguage?q5J(r,H.translationLanguage):r)}R.hT(H.position);!V||V===R.A&&R.loaded||(H=g.Sz(),h=g.aO(V),H.length&&h===H[H.length-1]||(H.push(h),g.vb("yt-player-caption-language-preferences",
H)),Ljp(R.O)&&!R.j.isInline()&&g.vb("yt-player-caption-sticky-language",h,2592E3),uj(R,V,!0))}else return R.loaded&&R.A&&!RW(R)?aY(R.A):{};return""};
g.dR.prototype.Mq=g.Sp(119,function(R,H,h){this.A.set(R,{Hb:H,vr:h})});
g.Ik.prototype.Mq=g.Sp(118,function(R,H,h){this.Mt.Mq(R,H,h)});
g.nN.prototype.C=g.Sp(117,function(){this.mediaElement.C()});
g.dP.prototype.C=g.Sp(116,function(){var R=g.u$(document,"track",void 0,this.V);for(let H=0;H<R.length;H++)g.KK(R[H])});
g.nN.prototype.hL=g.Sp(115,function(){return this.mediaElement.hL()});
g.dP.prototype.hL=g.Sp(114,function(){return!(!this.V.textTracks||!this.V.textTracks.addEventListener)});
g.nN.prototype.SR=g.Sp(113,function(){return this.mediaElement.SR()});
g.dP.prototype.SR=g.Sp(112,function(){return!!this.V.textTracks});
g.nN.prototype.Pd=g.Sp(111,function(R){this.mediaElement.Pd(R)});
g.dP.prototype.Pd=g.Sp(110,function(R){for(let H=0;H<R.length;H++)this.V.appendChild(R[H])});
g.DR.prototype.TY=g.Sp(46,function(R,H){this.app.C2().TY(R,H)});
g.cP.prototype.TY=g.Sp(45,function(R,H){this.D.TY(R,H)});
g.gR.prototype.TY=g.Sp(44,function(R,H){R=[R,H];g.cY(this,g.DT(this.provider),"cfi",R)});
g.sg.prototype.TY=g.Sp(43,function(R,H){this.qoe&&this.qoe.TY(R,H)});
g.Tq.prototype.TY=g.Sp(42,function(R,H){this.vx.TY(R,H)});
g.l_.prototype.TY=g.Sp(41,function(){});
g.DR.prototype.hJ=g.Sp(40,function(R,H,h){this.app.C2().hJ(R,H,h)});
g.cP.prototype.hJ=g.Sp(39,function(R,H,h){this.D.hJ(R,H,h)});
g.gR.prototype.hJ=g.Sp(38,function(R,H,h){if(this.DD!==R||this.Bx!==H)H=H==="rawcc"?"":H,h=[R,H,this.DD,h],g.cY(this,g.DT(this.provider),"cfs",h),this.DD=R,this.Bx=H});
g.sg.prototype.hJ=g.Sp(37,function(R,H,h){this.qoe&&this.qoe.hJ(R,H,h)});
g.Tq.prototype.hJ=g.Sp(36,function(R,H,h){this.vx.hJ(R,H,h)});
g.l_.prototype.hJ=g.Sp(35,function(){});
g.s9.prototype.Rq=g.Sp(9,function(){return this.XI});
g.ny.prototype.Rq=g.Sp(8,function(){return this.C2().UR()});
g.DR.prototype.UR=g.Sp(7,function(){return this.app.Rq()});
g.cP.prototype.UR=g.Sp(6,function(){return this.D.UR()});
g.Tq.prototype.UR=g.Sp(5,function(){return this.loader?.Rq()||null});
g.l_.prototype.UR=g.Sp(4,function(){return null});
g.yp.prototype.F1=g.Sp(2,function(R){return(R=this.L(R))?R.V:0});
g.HU.prototype.F1=g.Sp(1,function(){return 0});
var ibp=/#(.)(.)(.)/,BpC=/^#(?:[0-9a-f]{3}){1,2}$/i,Sg9={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},C3Q=class{constructor(){this.L=[];this.A=[]}V(R){return R?this.A.concat(this.L):this.A}},Ts=class extends g.Q{constructor(R){super();this.lI=R;this.V=new C3Q;this.Mt=new C3Q;this.S=null;this.C=[];this.Pd=[]}J(){}Y(){}L(){}X(){return""}gg(){return!1}hE(R,H){if(this.lI.U().G("html5_dispatch_tracklist_loaded_event")){this.S&&(this.S.reject(),this.S=null);var h=[];this.lI.n2("trackListLoaded",
this.V,h,H);this.lI.U().G("enable_po_decoration_of_forced_tracks")&&this.lI.n2("trackListLoaded",this.Mt,h,H);h.length?(H=new g.T2,H.promise.then(R.hE,()=>{}),this.S=H,Promise.all(h).then(H.resolve,H.reject).finally(()=>{this.S=null})):R.hE()}else R.hE()}Hd(){this.S&&(this.S.reject(),this.S=null);
this.L();super.Hd()}},zwW={en:"English"},E1a=class extends Ts{constructor(R){super(R);this.A=new Set}Y(R){var H=this.lI.Hg();if(H&&H.vg()){H=H.vg().textTracks;for(let h of H)h.kind==="subtitles"&&!this.A.has(h.language)&&h.language&&(Q8(this.V,new g.vM({languageCode:h.language,languageName:h.language,kind:h.kind,id:h.id,displayName:zwW[h.label]||h.label,vss_id:`.${h.language}`})),this.A.add(h.language))}this.V.V().length>0&&R.hE()}},KVa=class extends Ts{constructor(R,H,h){super(R);this.videoData=
H;this.audioTrack=h;this.A=null;this.N=!1;this.C=H.rQ;this.Pd=H.Jf;this.N=g.Xb(H)}J(R,H,h){this.YJ();H=this.X(R,H);var V=this.lI.U().G("html5_report_captions_ctmp_qoe"),S=(0,g.W)();this.L();fMJ(this,H,{format:"RAW",onSuccess:r=>{this.A=null;if(V){var k=(r.responseText.length/1024).toFixed();let u=(0,g.W)();this.videoData.B("capresp",{ms:u-S,kb:k})}k=r.getResponseHeader&&r.getResponseHeader("Content-Length")?Number(r.getResponseHeader("Content-Length")):0;h.Ho(r.responseText,R,void 0,void 0,k)},
onError:V?r=>{this.videoData.B("capfail",{status:r?.status??0})}:void 0,
withCredentials:!0})}Y(R){if(this.audioTrack){for(let H of this.audioTrack.captionTracks)Q8(this.V,H);this.audioTrack.V&&Q8(this.Mt,this.audioTrack.V)}this.hE(R,this.videoData.videoId)}X(R,H){var h=R.V9(),V={fmt:H};if(H==="srv3"||H==="3"||H==="json3")g.rg()?Object.assign(V,{xorb:2,xobt:1,xovt:1}):Object.assign(V,{xorb:2,xobt:3,xovt:3});R.translationLanguage&&(V.tlang=g.aO(R));this.N&&(V.xosf="1");Object.assign(V,this.lI.U().V);return g.cF(h,V)}L(){this.A&&this.A.abort()}},tvU=class{constructor(){this.segments=
[]}contains(R){R=g.VP(this.segments,R);return R>=0||R<0&&(-R-1)%2===1}length(){return this.segments.length/2}},a_a=class extends g.Q{constructor(R,H,h,V,S,r){super();this.policy=R;this.player=H;this.Vs=h;this.N=V;this.S=S;this.W=r;this.Y=new tvU;this.X=-1;this.A=this.L=this.V=null;this.Pd=0;this.J=new g.V2(this.C,1E3,this);this.events=new g.hC(this);g.N(this,this.J);g.N(this,this.events);this.events.Qs(H,"SEEK_COMPLETE",this.K);this.K();this.C()}Hd(){super.Hd();this.A&&this.A.cancel()}K(){this.seekTo(this.player.getCurrentTime())}seekTo(R){R-=
this.player.I3();var H=this.V;this.V=g.ZD(this.Vs.X(R).K2);H!==this.V&&this.W&&this.W()}reset(){this.Y=new tvU;this.X=-1;this.A&&(this.A.cancel(),this.A=null)}C(){this.YJ();var R;if(R=this.V!=null)R=this.V,R=R.Vs.Y(R);if(R&&!this.A&&!(this.V&&this.V.startTime-this.player.getCurrentTime()>30)){R=this.V;R=R.Vs.SR(R);let S=R.K2[0];if(this.player.getVideoData()?.enableServerStitchedDai){var H=this.player.UR();if(H){var h=S.Vs.info.id;let r=S.Fu;var V=R.K2[0].L;if(this.policy.rg){if(H=g.CS(H,V,r,h,3))R.Y=
H}else if(h=H.Qd(V,r,h,3))if(V=2,H.Zh.has(r)?V=0:g.cs(H,r)&&(V=1),H=V,H===0)h&&(R.V=new g.oR(h));else if(H===2){this.J.start();Roy(this)&&this.seekTo(this.player.getCurrentTime());return}}}S.Vs.index.kW(S.Fu)?(this.Y.contains(R.K2[0].Fu)||Hyp(this,R),this.V=g.ZD(R.K2)):Roy(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()}},Mvy=class extends Ts{constructor(R,H){super(H);this.A=R;this.j=H;this.N=null;this.K=!1;this.logger=new g.RD("caps");this.W=g.eH(this.j,this.A)}J(R,H,h){this.L();
H=hor(this,R.getId());H||(H=R.languageCode,H=this.A.isManifestless?VjC(this,H,"386"):VjC(this,H));if(H){var V=(H.index.F1(H.index.d0())-H.index.getStartTime(H.index.d0()))*1E3,S=new g.c8y(this.j.U());this.N=new a_a(S,this.j,H,(r,k)=>{h.Ho(r,R,k,V)},this.W||g.S6(H.info),()=>{this.N&&this.N.reset();
this.K=!0})}}gg(){var R=this.K;
this.K=!1;return R}Y(R){var H=this.j.U().G("html5_fallback_if_rawcc_missing");var h=this.A.V.rawcc!=null;if(!this.W||!h&&H)H=this.A.isManifestless?rCy(this,"386"):rCy(this);else{if(!h){g.Hj(this.logger,386248249,"rawcc used but unavailable");return}H=[new g.vM({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.vM({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let V of H)Q8(this.V,
V);R.hE()}L(){this.N&&(this.N.dispose(),this.N=null)}X(){return""}},g1J=class extends Ts{constructor(R,H,h,V,S,r){super(R);this.videoId=h;this.K=S;this.eventId=r;this.W={};this.A=null;R=V||g.bx(H).hl||"";R=R.split("_").join("-");this.N=g.cF(H,{hl:R})}J(R,H,h){this.YJ();H=this.X(R,H);this.L();this.A=g.Ab(H,{format:"RAW",onSuccess:V=>{this.A=null;var S=V.getResponseHeader&&V.getResponseHeader("Content-Length")?Number(V.getResponseHeader("Content-Length")):0;h.Ho(V.responseText,R,void 0,void 0,S)},
withCredentials:!0})}Y(R){var H=this.N,h={type:"list",tlangs:1,v:this.videoId,vssids:1};this.K&&(h.asrs=1);H=g.cF(H,h);this.L();this.A=g.Ab(H,{format:"RAW",onSuccess:V=>{this.A=null;if((V=V.responseXML)&&V.firstChild){var S=V.getElementsByTagName("track");for(var r=0;r<S.length;r++){var k=S[r],u=k.getAttribute("lang_code");let b=k.getAttribute("lang_translated"),T=k.getAttribute("name"),c=k.getAttribute("kind"),e=k.getAttribute("id"),D=k.getAttribute("lang_default")==="true",p=k.getAttribute("cantran")===
"true";k=k.getAttribute("vss_id");Q8(this.V,new g.vM({languageCode:u,languageName:b,name:T,kind:c,id:e,is_servable:!0,is_translateable:p,vss_id:k,is_default:D}))}V=V.getElementsByTagName("target");S=V.length;for(r=0;r<S;r++)u={languageCode:V[r].getAttribute("lang_code"),languageName:V[r].getAttribute("lang_translated"),languageOriginal:V[r].getAttribute("lang_original"),id:V[r].getAttribute("id"),isDefault:V[r].getAttribute("lang_default")==="true"},this.W[u.languageCode]=u.languageName,this.C.push(u)}this.hE(R,
this.videoId)},
withCredentials:!0})}X(R,H){var h=this.N;H={v:this.videoId,type:"track",lang:R.languageCode,name:R.getName(),kind:R.kind,fmt:H};var V=this.lI.U();V.G("captions_url_add_ei")&&(H.ei=this.eventId);R.translationLanguage&&(H.tlang=g.aO(R));Object.assign(H,V.V);return h=g.cF(h,H)}L(){this.A&&this.A.abort()}},qW=/^#(?:[0-9a-f]{3}){1,2}$/i;var FVp=["left","right","center","justify"];var bj=class extends g.sK{constructor(R,H,h,V,S,r,k,u,b,T){var c=T.isInline()&&!0,e={};Object.assign(e,H);Object.assign(e,R.params);Object.assign(e,h);var D={};Object.assign(D,H.Ym);R.params.Ym&&Object.assign(D,R.params.Ym);Object.assign(D,h.Ym);c&&(e.windowOpacity=.6,D.backgroundOpacity=0);e.Ym=D;var p=e.qd===1,K=[{Z:"span",oB:"captions-text",qt:{style:"word-wrap: normal; display: block;"}}],F=u.dg("caption_edit_on_hover")&&T.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
F&&K.unshift({Z:"button",oB:"caption-edit",qt:{tabindex:"0","aria-label":Uby()},ys:[{Z:"svg",qt:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},ys:[{Z:"path",qt:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({Z:"div",oB:"caption-window",qt:{id:`caption-window-${R.id}`,dir:p?"rtl":"ltr",tabindex:"0",lang:e.lang},ys:K});
this.N=[];this.hL=!1;this.L=R;this.Eh=this.Nt=null;this.Js=r;this.fG=k;this.C=null;this.maxWidth=r*.96;this.maxHeight=k*.96;this.V=e;this.Kf=h;this.gg=H;this.X=this.JL("captions-text");R=this.X.style;this.Dq=u.dg("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in R||"WebkitBoxDecorationBreak"in R);this.kJ=kHQ(V,S,r,k);this.j2=b;F&&(this.J=this.JL("caption-edit"),this.Qs(this.J,"click",()=>{this.j2()}));
this.type=0;this.Uh=this.kJ*uNr(D);this.O1=c;this.jR=u.dg("enable_centered_caption_for_tvfilm_video")&&T.getVideoData().isTvfilmVideo;this.W=T.U().f2().V.zp(g.Vry);V=new g.XN(this.element,!0);g.N(this,V);V.subscribe("dragstart",this.Uv,this);V.subscribe("dragmove",this.dl,this);V.subscribe("dragend",this.CG,this);this.ww=this.yj=this.uK=this.lK=0;V="";this.V.windowOpacity&&(V=gn(this.V.windowColor),V="rgba("+V[0]+","+V[1]+","+V[2]+","+this.V.windowOpacity+")");S={"background-color":V,display:this.V.isVisible===
!1?"none":"","text-align":FVp[this.V.textAlign]};this.Dq&&(S["border-radius"]=V?`${this.Uh*.375}px`:"");(this.S=this.L.params.qd===2||this.L.params.qd===3)&&by4(this,this.element);g.dX(this.element,S);c&&this.element.parentElement?.style.setProperty("--caption-window-color",V);switch(this.V.Su){case 0:case 1:case 2:g.Tn(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Tn(this.element,"ytp-caption-window-bottom")}}Uv(R,H){this.yj=R;this.ww=H;var h=g.Bx(this.element,this.element.parentElement);
this.lK=R-h.x;this.uK=H-h.y}dl(R,H){if(R!==this.yj||H!==this.ww){g.bB(this.element,"ytp-dragging")||g.Tn(this.element,"ytp-dragging");var h=g.fA(this.element);R=R-this.lK-.02*this.Js;var V=H-this.uK-.02*this.fG,S=(R+h.width/2)/this.maxWidth*3;S=Math.floor(g.Y6(S,0,2));var r=(V+h.height/2)/this.maxHeight*3;r=Math.floor(g.Y6(r,0,2));H=S+r*3;R=(R+S/2*h.width)/this.maxWidth;R=g.Y6(R,0,1)*100;h=(V+r/2*h.height)/this.maxHeight;h=g.Y6(h,0,1)*100;this.L.params.Su=H;this.L.params.ER=h;this.L.params.FD=R;this.L.params.isDefault=
!1;this.V.Su=H;this.V.ER=h;this.V.FD=R;this.V.isDefault=!1;this.gg.Su=H;this.gg.ER=h;this.gg.FD=R;this.gg.isDefault=!1;this.hC()}}CG(){g.eK(this.element,"ytp-dragging")}hC(){this.K(this.N)}K(R){var H=this.O1?0:Math.min(this.Bx(),this.maxWidth),h=this.R3(),V=this.O1;if(V){var S=getComputedStyle(this.X.parentNode);S=s4(S.borderLeftWidth)+s4(S.borderRightWidth)+s4(S.paddingLeft)+s4(S.paddingRight)}else S=0;var r=S;S="";this.L.params.qd===3&&(S="rotate(180deg)");var k=V?`calc(96% - ${r}px)`:"96%";g.dX(this.element,
{top:0,left:0,right:"",bottom:"",width:H?`${H}px`:"",height:h?`${h}px`:"","max-width":k,"max-height":k,margin:"",transform:""});this.DD(R);S={transform:S,top:"",left:"",width:H?`${H}px`:"",height:h?`${h}px`:"","max-width":"","max-height":""};k=this.V.Su;var u=this.V.FD,b=this.V.ER;this.jR&&k!=null&&(u=50,k=Math.floor(k/3)*3+1);u=u*.96+2;switch(k){case 0:case 3:case 6:(V=this.V.Ym.fontSizeIncrement)&&V>0&&this.V.qd!==2&&this.V.qd!==3&&(u=Math.max(u/(1+V*2),2));S.left=`${u}%`;break;case 1:case 4:case 7:S.left=
`${u}%`;u=0;this.W||(u=this.X.offsetWidth);H||u?(H=H||u+1,S.width=`${H}px`,S["margin-left"]=V?`${H/-2-r/2}px`:`${H/-2}px`):(this.W&&(S.width="max-content"),S.transform+=" translateX(-50%)");break;case 2:case 5:case 8:S.right=`${100-u}%`}V=b*.96+2;switch(k){case 0:case 1:case 2:S.top=`${V}%`;break;case 3:case 4:case 5:S.top=`${V}%`;V=0;this.W||(V=this.element.clientHeight);(h=h||V)?(S.height=`${h}px`,S["margin-top"]=`${h/-2}px`):S.transform+=" translateY(-50%)";break;case 6:case 7:case 8:S.bottom=
`${100-V}%`}g.dX(this.element,S);if(this.J){if(this.W)h=this.Uh;else{if(this.jR&&R.length===0)R=0;else{h=1;for(V=0;V<R.length;V++)S=R[V],typeof S.text==="string"&&(h+=S.text.split("\n").length-1,S.append||V===0||h++);R=h}h=this.jR?R>0?this.X.offsetHeight/R:0:this.X.offsetHeight/R}this.J.style.height=`${h}px`;this.J.style.width=`${h}px`;this.element.style.paddingLeft=`${h+5}px`;this.element.style.paddingRight=`${h+5}px`;this.W||(R=Number(this.element.style.marginLeft.replace("px",""))-h-5,h=Number(this.element.style.marginRight.replace("px",
""))-h-5,this.element.style.marginLeft=`${R}px`,this.element.style.marginRight=`${h}px`)}}DD(R){var H;for(H=0;H<R.length&&R[H]===this.N[H];H++);if(this.hL||this.N.length>H)H=0,this.hL=!1,this.N=[],this.C=this.Eh=this.Nt=null,g.zE(this.X);for(;H<R.length;H++)Dxy(this,R[H])}Bx(){return 0}R3(){return 0}toString(){return super.toString()}};var N0y=class{constructor(){this.L=this.time=this.mode=this.A=0;this.Y=new QEj(this);this.S=new QEj(this);this.V=[];this.clear()}clear(){this.L=this.time=this.mode=0;this.V=[];this.reset()}reset(){this.mode=0;this.Y.reset(0);this.S.reset(1)}},pUa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],sE4=class{constructor(){this.type=0}set(R){this.type=R}get(){return this.type}},P3J=class{constructor(){this.state=this.QN=this.kB=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}AP(){return this.state!==0}matches(R,H){return this.AP()&&R===this.kB&&H===this.QN}},XRy=class{constructor(){this.timestamp=this.V=0}reset(){this.timestamp=
this.V=0}},c9=class{constructor(R){this.S=R;this.L=[];this.V=this.A=this.row=0;this.style=new sE4;this.Y=0;for(R=0;R<=15;R++){this.L[R]=[];for(let H=0;H<=32;H++)this.L[R][H]=new XRy}}updateTime(R){for(let H=1;H<=15;++H)for(let h=1;h<=32;++h)this.L[H][h].timestamp=R}debugString(){var R="\n";for(let H=1;H<=15;++H){for(let h=1;h<=32;++h){let V=this.L[H][h];R=V.V===0?R+"_":R+String.fromCharCode(V.V)}R+="\n"}return R}reset(R){for(let H=0;H<=15;H++)for(let h=0;h<=32;h++)this.L[H][h].reset();this.Y=R;this.V=
0;this.A=this.row=1}},GHC=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],C_J=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],zop=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],EFr=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],A2Q=class{constructor(R){this.L=R;this.S=0;this.style=new sE4;this.X=new c9(this.L);this.J=new c9(this.L);this.text=new c9(this.L);this.A=this.X;this.Y=this.J;this.V=this.A}reset(R,H){this.S=H;this.style.set(2);this.A=this.X;this.Y=this.J;this.V=this.A;var h=(R<<2)+(H<<1);this.X.reset(h);this.J.reset(h);this.text.reset((R<<
2)+(H<<1)+1)}},QEj=class{constructor(R){this.V=R;this.S=0;this.L=new A2Q(this.V);this.X=new A2Q(this.V);this.A=new P3J;this.Y=this.L}reset(R){this.S=R;this.A.clear();this.Y=this.L;this.L.reset(R,0);this.X.reset(R,1)}};var ZsQ=class{Y(){}};var O4=class extends g.BW{constructor(R,H,h,V,S,r=!1,k=null){super(R,R+H,{priority:h,namespace:"captions"});this.windowId=V;this.text=S;this.append=r;this.V=k}toString(){return super.toString()}};var eq=class extends g.Q{reset(){}};var IY=class extends g.BW{constructor(R,H,h,V,S){super(R,R+H,{priority:h,namespace:"captions"});this.id=V;this.params=S;this.V=[]}toString(){return super.toString()}},dn=0;var l_4=class extends eq{constructor(R){super();this.Y=R;this.pens={};this.N={};this.C={};this.S="_"+dn++;this.J={};this.A=this.V=null;this.X=!0}reset(){this.J={};this.A=this.V=null;this.X=!0}L(R,H){R=R.firstChild;R.getAttribute("format");H=H||0;Number.isFinite(H);R=Array.from(R.childNodes);for(var h of R)if(h.nodeType===1)switch(h.tagName){case "head":var V=h;break;case "body":var S=h}if(V){V=Array.from(V.childNodes);for(var r of V)if(r.nodeType===1)switch(r.tagName){case "pen":h=r.getAttribute("id");
V=this.pens;R={};var k=r.getAttribute("p");k&&Object.assign(R,this.pens[k]);k=Jh(r,"b");k!=null&&(R.bold=k);k=Jh(r,"i");k!=null&&(R.italic=k);k=Jh(r,"u");k!=null&&(R.underline=k);k=nW(r,"et");k!=null&&(R.charEdgeStyle=k);k=nW(r,"of");k!=null&&(R.offset=k);k=LW(r,"bc");k!=null&&(R.background=k);k=LW(r,"ec");k!=null&&(R.z4=k);k=LW(r,"fc");k!=null&&(R.color=k);k=nW(r,"fs");k!=null&&k!==0&&(R.fontFamily=k);k=oY(r,"sz");k!==void 0&&(R.fontSizeIncrement=k/100-1);k=oY(r,"bo");k!==void 0&&(R.backgroundOpacity=
k/255);k=oY(r,"fo");k!==void 0&&(R.textOpacity=k/255);k=nW(r,"rb");k!=null&&k!==10&&k!==0&&(R.IT=k>10?k-1:k);k=nW(r,"hg");k!=null&&(R.I7=k);V[h]=R;break;case "ws":V=r.getAttribute("id");this.C[V]=NRJ(this,r);break;case "wp":V=r.getAttribute("id"),this.N[V]=skj(this,r)}}if(S){r=[];S=Array.from(S.childNodes);for(F of S)if(F.nodeType===1)switch(F.tagName){case "w":this.V=P_U(this,F,H,!1);(S=this.J[this.V.id])&&S.end>this.V.start&&(S.end=this.V.start);this.J[this.V.id]=this.V;r.push(this.V);break;case "p":var u=
F;R=H;S=[];V=u.getAttribute("w")||this.S;h=!!Jh(u,"a");R=(oY(u,"t")||0)+R;k=oY(u,"d")||5E3;h||(!this.X&&this.A&&this.A.windowId===V&&this.A.end>R&&(this.A.end=R),this.A&&this.A.text==="\n"&&(this.A.text=""));let X=h?6:5;var b=u.getAttribute("p");b=b?this.pens[b]:null;let Z=Array.from(u.childNodes);Z.length&&(this.X=u.getAttribute("d")!=null);for(u=0;u<Z.length;u++){var T=Z[u],c=void 0;u>0&&(h=!0);let l;T.nodeType===1&&(l=T);if(l&&l.tagName==="s"){if((T=(T=l.getAttribute("p"))?this.pens[T]:null)&&
T.IT&&(T.IT===1?(T=Z.slice(u,u+4),T.length===4&&(c=FfG(R,k,V,h,X,T,this.pens),u+=3)):c=FfG(R,k,V,h,X,[l],this.pens)),!c){var e=l;c=R;T=k;var D=V,p=h;let n=e.textContent?e.textContent:"";var K=e.getAttribute("p");K=K?this.pens[K]:null;e=oY(e,"t")||0;c=new O4(c+e,T-e,X,D,n,p,K)}}else c=new O4(R,k,X,V,T.textContent||"",h,b);S.push(c);this.A=c}if(S.length>0){S[0].windowId===this.S&&(this.V=P_U(this,F,H,!0),r.push(this.V));for(let l of S)l.windowId=this.V.id,this.V.V.push(l),r.push(l)}}var F=r}else F=
[];return F}};var wRW=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),OsU=class extends eq{constructor(R){super();this.X=R;this.V=new Map;this.Y=new Map;this.S=new Map;this.A=new Map}reset(){this.A.clear()}L(R,H){R=JSON.parse(R);if(!R)return[];if(R.pens){var h=R.pens,V=0;for(var S of h){h={};var r=S.pParentId;r&&Object.assign(h,this.V.get(r));S.bAttr&&(h.bold=!0);S.iAttr&&(h.italic=!0);S.uAttr&&(h.underline=!0);r=S.ofOffset;r!=null&&(h.offset=r);S.szPenSize!==void 0&&(h.fontSizeIncrement=S.szPenSize/100-1);
r=S.etEdgeType;r!=null&&(h.charEdgeStyle=r);S.ecEdgeColor!==void 0&&(h.z4=WG(S.ecEdgeColor));r=S.fsFontStyle;r!=null&&r!==0&&(h.fontFamily=r);S.fcForeColor!==void 0&&(h.color=WG(S.fcForeColor));S.foForeAlpha!==void 0&&(h.textOpacity=S.foForeAlpha/255);S.bcBackColor!==void 0&&(h.background=WG(S.bcBackColor));S.boBackAlpha!==void 0&&(h.backgroundOpacity=S.boBackAlpha/255);(r=S.rbRuby)&&r!==10&&(h.IT=r>10?r-1:r,h.textEmphasis=wRW.get(h.IT));S.hgHorizGroup&&(h.I7=S.hgHorizGroup);this.V.set(V++,h)}}if(R.wsWinStyles){V=
R.wsWinStyles;S=0;for(var k of V)V={},(h=k.wsParentId)?Object.assign(V,this.S.get(h)):Object.assign(V,this.X),k.mhModeHint!==void 0&&(V.Oz=k.mhModeHint),k.juJustifCode!==void 0&&(V.textAlign=k.juJustifCode),k.pdPrintDir!==void 0&&(V.qd=k.pdPrintDir),k.sdScrollDir!==void 0&&(V.pL=k.sdScrollDir),k.wfcWinFillColor!==void 0&&(V.windowColor=WG(k.wfcWinFillColor)),k.wfoWinFillAlpha!==void 0&&(V.windowOpacity=k.wfoWinFillAlpha/255),this.S.set(S++,V)}if(R.wpWinPositions){S=R.wpWinPositions;k=0;for(var u of S)S=
{},(V=u.wpParentId)&&Object.assign(S,this.Y.get(V)),u.ahHorPos!==void 0&&(S.FD=u.ahHorPos),u.apPoint!==void 0&&(S.Su=u.apPoint),u.avVerPos!==void 0&&(S.ER=u.avVerPos),u.ccCols!==void 0&&(S.VN=u.ccCols),u.rcRows!==void 0&&(S.IY=u.rcRows),this.Y.set(k++,S)}if(R.events){R=R.events;u=[];for(let I of R)if(k=(I.tStartMs||0)+H,S=I.dDurationMs||0,I.id)V=String(I.id),R=XUy(this,I,k,S,V),u.push(R),this.A.set(V,R);else{I.wWinId?V=I.wWinId.toString():(V="_"+dn++,R=XUy(this,I,k,S,V),u.push(R),this.A.set(V,R));
R=u;var b=I;S===0&&(S=5E3);h=this.A.get(V);let H4=(r=!!b.aAppend)?6:5,$9=b.segs,DJ=null;b.pPenId&&(DJ=this.V.get(b.pPenId));for(b=0;b<$9.length;b++){var T=$9[b],c=T.utf8;if(c){var e=T.tOffsetMs||0;let tU=null;T.pPenId&&(tU=this.V.get(T.pPenId));if((h.params.Oz!=null?h.params.Oz:h.V.length>1?1:0)===2&&r&&c==="\n")continue;T=null;var D=[],p;if(p=tU&&tU.IT===1)a:{p=$9;var K=b;if(K+3>=p.length||!p[K+1].pPenId||!p[K+2].pPenId||!p[K+3].pPenId){p=!1;break a}var F=p[K+1].pPenId;(F=this.V.get(F))&&F.IT&&F.IT===
2?(F=p[K+2].pPenId,F=this.V.get(F),!F||!F.IT||F.IT<3?p=!1:(F=p[K+3].pPenId,p=(F=this.V.get(F))&&F.IT&&F.IT===2?!0:!1)):p=!1}if(p)e=$9[b+1].utf8,T=$9[b+3].utf8,p=$9[b+2].utf8,K=this.V.get($9[b+2].pPenId),c=gFJ(c,e,p,T,K),T=new O4(k,S,H4,V,c,r,tU),b+=3;else{if(c.indexOf("<")>-1){D=tU;p=DJ;K=k;F=S;var X=e,Z=H4,l=r;let Uj=[];var n=NW(`<html>${c}</html>`);if(!n.getElementsByTagName("parsererror").length&&n.firstChild?.childNodes.length)for(let JU of n.firstChild.childNodes){n=JU.textContent?.replace(/\n/g,
"")??"";if(JU.nodeType===3&&(!n||n.match(/^ *$/)!=null))continue;let Tj={};Object.assign(Tj,D||p);switch(JU?.tagName){case "b":Tj.bold=!0;break;case "i":Tj.italic=!0;break;case "u":Tj.underline=!0}Uj.push(new O4(K+X,F-X,Z,h.id,n,l,Tj))}D=Uj}D.length||(D=[new O4(k+e,S-e,H4,h.id,c,r,tU||DJ)])}if(D.length)for(let Uj of D)R.push(Uj),h.V.push(Uj);else T&&(R.push(T),h.V.push(T))}r=!0}}H=u}else H=[];return H}};var dUQ=class extends Ts{constructor(R,H,h){super(R);this.videoData=H;this.audioTrack=h;this.C=H.rQ}J(R,H,h){xba(this.videoData.videoId,R.vssId,h.Ho)}Y(R){if(this.audioTrack)for(let H of this.audioTrack.captionTracks)Q8(this.V,H);R.hE()}};var YtQ=class extends bj{constructor(R,H,h,V,S,r,k,u,b,T){super(R,H,h,V,S,r,k,u,b,T);this.type=1}DD(R){var H=this.L.V;super.DD(R);for(R=R.length;R<H.length;R++){let S=H[R],r;if(V&&S.V===h)r=V;else{r={};Object.assign(r,S.V);Object.assign(r,I_j);var h=S.V;var V=r}Dxy(this,S,r)}}},I_j={OQ:!0};var ACp=class extends ZsQ{constructor(R,H){super();this.trackData=R;this.X=H;this.version=this.S=this.L=this.byteOffset=0;this.A=[];this.V=new DataView(this.trackData)}Y(R,H,h,V,S){if(h<V){let r="_"+dn++;h=h/1E3-this.X;V=V/1E3-this.X;R=new IY(h,V-h,5,r,{textAlign:0,Su:0,FD:H*2.5,ER:R*5.33});S=new O4(h,V-h,5,r,S);this.A.push(R);this.A.push(S)}}},J2j=class extends eq{constructor(R,H){super();this.A=R;this.Y=H;this.track=this.Y.languageName==="CC3"?4:0;this.V=new N0y;this.V.A=1<<this.track}L(R){R=new ACp(R,
this.A);if(Zyy(R)){for(;R.byteOffset<R.V.byteLength;)for(R.version===0?R.L=BG(R)*(1E3/45):R.version===1&&(R.L=BG(R)*4294967296+BG(R)),R.S=x8(R);R.S>0;R.S--){var H=x8(R);let h=x8(R),V=x8(R);H&4&&(H&3)===this.track&&(this.track===0||this.track===1)&&(H=this.V,H.V.push({time:R.L,type:this.track,AB:h,yk:V,order:H.V.length}))}jkW(this.V,R);return R.A}return[]}reset(){this.V.clear()}};var jEC=class extends bj{constructor(R,H,h,V,S,r,k,u,b,T){super(R,H,h,V,S,r,k,u,b,T);this.type=2;this.rg=[];this.Mt=this.Pd=this.Oh=0;this.SR=NaN;this.nf=0;this.Tr=null;this.uZ=new g.V2(this.Wd,433,this);this.J&&(T.createClientVe(this.J,this,167342),this.Qs(this.J,"click",()=>{T.logClick(this.J)}),R=new g.XN(this.element,!0),g.N(this,R),R.subscribe("hoverstart",()=>{T.logVisibility(this.J,!0)},this));
g.Tn(this.element,"ytp-caption-window-rollup");g.N(this,this.uZ);g.dX(this.element,"overflow","hidden")}hC(){var R=this.uZ;R.stop();R.UW()}Wd(){this.element.removeEventListener("transitionend",this.Wd,!1);g.eK(this.element,"ytp-rollup-mode");this.K(this.Tr,!0)}R3(){return this.S?this.Mt:this.Pd}Bx(){return this.S?this.Pd:this.Mt}K(R,H){this.Tr=R;if(this.L.params.IY){var h=0;for(let V=0;V<this.N.length&&h<R.length;V++)this.N[V]===R[h]&&h++;h>0&&h<R.length&&(R=this.N.concat(R.slice(h)));this.nf=this.Mt;
this.Pd=this.Mt=0;super.K(R);dx3(this,H)}super.K(R)}};var n14=class{constructor(R,H,h,V){this.j=R;this.X=H;this.logger=h;this.L4=V;this.bZ=[];this.V=null;this.L=[];this.LW=[];this.A=null;R=g.zk(this.j.U().experiments,"html5_override_micro_discontinuities_threshold_ms");this.Y=R>0?R:10}unload(){this.A!=null&&(this.j.removeEventListener("sabrCaptionsDataLoaded",this.A),this.A=null);this.bZ=[];this.V=null;this.L=[];this.j.n2("sabrCaptionsBufferedRangesUpdated",this.bZ)}S(R){return{formatId:g.pX(R.info.Vs.info,this.L4),Fu:R.info.Fu+(this.L4?0:1),startTimeMs:R.info.L*
1E3,durationMs:R.info.J*1E3}}};var qtr=class extends Ts{constructor(R,H){super(H);this.A=R;this.j=H;this.logger=new g.RD("caps");this.N=this.W=null;this.K=new n14(this.j,this,this.logger,this.A.L4)}J(R,H,h){this.L();H=R.getId();H=H!=null&&H in this.A.V?this.A.V[H]:null;H||(H=R.languageCode,H=this.A.isManifestless?Wfy(this,H,"386"):Wfy(this,H));H&&(this.N=R,this.W=H,qgj(this.K,h),this.j.n2("sabrCaptionsTrackChanged",g.pX(H.info,this.A.L4)))}Y(R){var H=this.A.isManifestless?xxa(this,"386"):xxa(this);for(let h of H)Q8(this.V,h);R.hE()}L(){this.N&&
(this.N=this.W=null,this.K.unload(),this.j.n2("sabrCaptionsTrackChanged",null))}X(){return""}};var BR3="WEBVTT".split("").map(R=>R.charCodeAt(0)),Rw3=class extends eq{constructor(){super()}L(R,H){R instanceof ArrayBuffer&&(R=g.L_(new Uint8Array(R)));
var h=[];R=R.split(LVW);for(let K=1;K<R.length;K++){var V=R[K],S=H;if(V!==""&&!WVQ.test(V)){var r=DU.exec(V);if(r&&r.length>=4){var k=i7(r[1]),u=i7(r[2])-k;k+=S;var b=(r=r[3])?r.split(" "):[];r={};var T=null;var c="";var e=null,D="";for(let F of b){b=F.split(":");if(b.length!==2)continue;var p=b[1];switch(b[0]){case "line":b=p.split(",");b[0].endsWith("%")&&(T=b[0],r.ER=Number.parseInt(T,10),b.length===2&&(c=b[1].trim()));break;case "position":b=p.split(",");e=b[0];r.FD=Number.parseInt(e,10);b.length===
2&&(D=b[1].trim());break;case "align":switch(p){case "start":r.textAlign=0;break;case "middle":r.textAlign=2;break;case "end":r.textAlign=1}}}T||c||(c="end");if(!e)switch(r.textAlign){case 0:r.FD=0;break;case 1:r.FD=100;break;case 2:r.FD=50}if(r.textAlign!=null){T=0;switch(c){case "center":T+=3;break;case "end":T+=6;break;default:T+=0}switch(D){case "line-left":T+=0;break;case "center":T+=1;break;case "line-right":T+=2;break;default:switch(r.textAlign){case 0:T+=0;break;case 2:T+=1;break;case 1:T+=
2}}c=T<0||T>8?7:T;r.Su=c}V=V.substring(DU.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");D=r;r={};if(V.indexOf("<")<0&&V.indexOf("&")<0)S=Uxa(k,u,5,D),k=new O4(k,u,5,S.id,V,!1,g.wk(r)?void 0:r),h.push(S),h.push(k),S.V.push(k);else for(c=V.split(xUa),c.length===1?(V=5,D=Uxa(k,u,V,D)):(T=V=6,D=Object.assign({VN:32},D),D=new IY(k,u,T,"_"+dn++,D)),h.push(D),T=k,e=0;e<c.length;e++)if(b=c[e],e%2===0){p=NW(`<html>${b}</html>`);let F;p.getElementsByTagName("parsererror").length?(F=p.createElement("span"),
F.appendChild(p.createTextNode(b))):F=p.firstChild;vFW(this,T,u-(T-k),V,D,e>0,F,r,h)}else T=i7(b)+S}DU.lastIndex=0}}return h}},WVQ=/^NOTE/,LVW=/(?:\r\n|\r|\n){2,}/,DU=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),xUa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var B0a=class extends g.Q{constructor(R,H){super();this.j=R;this.O=H;this.V=null;this.XI=this.j.UR();this.logger=new g.RD("caps")}clear(){this.V&&this.V.dispose();this.V=null}reset(){this.V&&this.V.reset()}Hd(){super.Hd();this.clear()}};var r2S={windowColor:"#080808",windowOpacity:0,textAlign:2,Su:7,FD:50,ER:100,isDefault:!0,Ym:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},StW={windowColor:"#080808",windowOpacity:0,textAlign:0,Su:7,FD:50,ER:100,isDefault:!0,Ym:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.c_("captions",class extends g.ZR{constructor(R){super(R);this.j=R;this.rg=[];this.Pd={};this.RB={};this.N=!1;this.L="NONE";this.V=this.C=this.K=this.Nt=this.jR=null;this.yj={hE:()=>{this.hE()},
Ho:(V,S,r,k,u=0)=>{var b=Number(this.videoData.U().f2().V.zp(g.eIC)??0);u>0&&b>0&&this.videoData.lengthSeconds>0&&u/this.videoData.lengthSeconds>b?this.j.B("tts",{dropcap:u}):this.Ho(V,S,r,k)}};
this.DD=this.A=null;this.O=this.j.U();this.videoData=this.j.getVideoData();this.bK=this.j.D2();this.S={Ym:{}};this.X={Ym:{}};g.oQ(this.videoData)?this.L="OFFLINE":g.vtG(this.videoData,this.j)?this.L="HLS":LfS(this.videoData,this.j)?this.L="SABR_LIVE":g.fBp(this.videoData,this.j)?this.L="LIVE":this.videoData.captionTracks.length?this.L="INNERTUBE":this.videoData.Dq&&(this.L="TTS");this.Eh=this.O.controlsType==="3";this.Oh=new B0a(this.j,this.O);this.Mt=new g.hC(this);this.J=new g.sK({Z:"div",oB:"ytp-caption-window-container",
qt:{id:"ytp-caption-window-container"}});this.W={top:0,right:0,bottom:0,left:0,width:1,height:1};var H=null,h=g.wt("yt-html5-player-modules::subtitlesModuleData");h&&(H=new g.tr(h));this.storage=H;this.Wd=!!R.Hg()?.hL();this.Y=VvC(this);this.gg=!this.Y&&this.Eh&&this.Wd&&(this.L==="LIVE"||this.L==="SABR_LIVE");g.N(this,this.Oh);this.Y?this.hL=this.SR=null:(this.SR=new g.R2(this.lK,void 0,this),g.N(this,this.SR),this.hL=new g.V2(this.nf,2E3,this),g.N(this,this.hL));g.N(this,this.Mt);g.ab(this.player,
this.J.element,4);g.N(this,this.J);this.Y||this.Mt.Qs(R,"resize",this.Uh);(this.ww=g.Lp(this.O)&&!g.wg()&&!this.j.isFullscreen()&&!this.Y&&!this.gg)&&this.Mt.Qs(R,"resize",this.O1);this.Mt.Qs(R,"onPlaybackAudioChange",this.uK);this.Mt.Qs(R,g.WW("captions"),V=>{this.onCueRangeEnter(V)});
this.Mt.Qs(R,g.x3("captions"),V=>{this.onCueRangeExit(V)});
U4(this,Fq()||{});g.V9(this.player,"onCaptionsModuleAvailable");this.L==="HLS"&&this.Y&&(R=this.j.Hg().vg(),this.Wd&&this.Mt.Qs(R.textTracks,"addtrack",this.R3))}Hd(){if(this.Y||this.gg){let R=this.j.Hg();R&&!R.YJ()&&R.C()}else vG(this,!1);super.Hd()}hM(){if(this.Eh)return this.Y||this.gg;if(this.L==="HLS")return this.Y;var R=this.getAudioTrack();if(T0p(this)){if(!R.captionTracks.length)return!1;if(!this.V)return!0}R=MW(R,g.TG(this.O));return R==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:R==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
y8(this):fW(this)||y8(this)?!0:bsC(this)}load(){super.load();this.C=this.getAudioTrack();if(this.V)this.A&&(this.Oh.clear(),this.Y?c2p(this,!0):this.player.getPresentingPlayerType()!==3&&this.V.J(this.A,"json3",this.yj),this.L!=="HLS"&&this.Y||this.gg||RW(this)||g.V9(this.player,"captionschanged",aY(this.A)));else{if(this.L==="OFFLINE")var R=new dUQ(this.player,this.videoData,this.getAudioTrack());else this.L==="SABR_LIVE"?R=new qtr(this.videoData.V,this.player):this.L==="HLS"?R=new E1a(this.player):
this.L==="LIVE"?R=new Mvy(this.videoData.V,this.player):this.L==="INNERTUBE"?R=new KVa(this.player,this.videoData,this.getAudioTrack()):(R=this.videoData,R=new g1J(this.player,this.videoData.Dq,this.videoData.videoId,R.captionsLanguagePreference||R.bI.captionsLanguagePreference||g.aQ(R,"yt:cc_default_lang")||R.bI.Wd,this.videoData.K3,this.videoData.eventId));this.V=R;g.N(this,this.V);this.V.Y(this.yj)}}unload(){this.Y&&this.A?c2p(this,!1):(this.hL&&this.hL.fQ(),this.player.FB("captions"),this.rg=
[],this.V&&this.V.L(),this.Oh.clear(),this.K&&this.player.ey(this.K),this.Uh());super.unload();this.player.NU();g.V9(this.player,"captionschanged",{})}create(){this.hM()&&this.load();var R;a:{if(this.O.G("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(R=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let H of R)if(H.kind==="asr"&&H.languageCode==="en"){R=
!0;break a}R=!1}R&&this.j.n2("showpromotooltip",this.J.element)}hE(){var R=MW(this.player.getAudioTrack(),g.TG(this.O));var H=R==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?hT(this,this.N):R==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&y8(this)?H9(this):fW(this)||this.N||bsC(this)?hT(this,this.N):y8(this)?H9(this):null;if(this.L!=="HLS"&&this.Y||this.gg){let h=this.V.V.V(!0);R=[];for(let V=0;V<h.length;V++){let S=h[V],r=g.GE("TRACK");r.setAttribute("kind","subtitles");r.setAttribute("label",g.tm(S));r.setAttribute("srclang",
g.aO(S));r.setAttribute("id",S.toString());this.gg||r.setAttribute("src",this.V.X(S,"vtt"));S===H&&r.setAttribute("default","1");R.push(r)}H=this.j.Hg();H.Pd(R);R=H.vg();this.Wd&&this.Mt.Qs(R.textTracks,"change",this.Yk)}else!this.A&&H&&uj(this,H),g.V9(this.player,"onCaptionsTrackListChanged"),g.Si(this.player,"onApiChange")}getTrackById(R){var H=this.V.V.V(!0);for(let h=0;h<H.length;h++)if(H[h].toString()===R)return H[h];return null}Yk(){var R=this.j.Hg().vg().textTracks,H=null;for(let h=0;h<R.length;h++)R[h].mode===
"showing"&&(H=this.getTrackById(R[h].id));(this.loaded?this.A:null)!==H&&uj(this,H,!0)}R3(){this.V?.Y(this.yj)}x5(){!this.A&&this.Y||this.unload()}Ho(R,H,h,V){if(R){kz(this,this.A??void 0);this.V.gg()&&(this.rg=[],this.j.FB("captions"),th(this.SR),this.Oh.reset());a:{var S=this.Oh;V=V||0;h=yCW(S,R,h||0);R=[];try{for(let Z of h){let l=Z.trackData,n=Z.aZ,I=S.O.G("safari_live_drm_captions_fix");if(typeof l!=="string"){h=R;var r=h.concat;if(I&&iy3(l))var k=HsW(S,l,n);else{var u=S,b=H,T=l,c=n,e=V;if(!lRG(T))throw Error("Invalid binary caption track data");
u.V||(u.V=new J2j(e,b));k=u.V.L(T,c)}var D=r.call(h,k)}else{if(l.substring(0,6)==="WEBVTT")var p=R.concat(HsW(S,l,n));else{h=R;var K=h.concat;b:{b=S;u=H;if(l[0]==="{")try{b.V||(b.V=new OsU(hwj(u)));var F=b.V.L(l,n);break b}catch(DJ){g.x(DJ);F=[];break b}let H4=NW(l);if(!H4||!H4.firstChild){let DJ=Error("Invalid caption track data");DJ.params=l;throw DJ;}if(H4.firstChild.tagName==="timedtext"){if(Number(H4.firstChild.getAttribute("format"))===3){T=H4;b.V||(b.V=new l_4(hwj(u)));F=b.V.L(T,n);break b}let DJ=
Error("Unsupported subtitles format in web player (Format2)");DJ.params=l;throw DJ;}if(H4.firstChild.tagName==="transcript"){let DJ=Error("Unsupported subtitles format in web player (Format1)");DJ.params=l;throw DJ;}let $9=Error("Invalid caption track data");$9.params=l;throw $9;}p=K.call(h,F)}D=p}R=D}var X=R;break a}catch(Z){g.Hj(S.logger,187101178,`Captions parsing failed: ${Z.message}. `);S.clear();X=[];break a}X=void 0}this.O.G("html5_sabr_live_support_subfragmented_captions")&&this.V instanceof
qtr&&(H=this.V.K,S=[],X.length>0&&(S=X.slice(H.L.length)),H.L=!H.V||H.V.info.S0?[]:X,X=S);X.length>0&&(H=this.A,this.hJ(H,!!H,RW(this)?"g":this.N?"m":"s"));this.player.ey(X,void 0,this.L==="LIVE"||this.L==="SABR_LIVE");!this.N||this.gg||RW(this)||g.Sa(this.O)||g.fp(this.O)||g.Wy(this.O)||this.O.C==="shortspage"||this.player.isInline()||(this.hL.fQ(),X=Qkr({Su:0,FD:5,ER:5,IY:2,textAlign:0,qd:0,lang:"en"}),this.Nt=[X],H=["Click "," for settings"],this.jR||(S=new g.WYW({Z:"svg",qt:{height:"100%",version:"1.1",
viewBox:"0 0 36 36",width:"100%"},ys:[{Z:"path",lP:!0,qt:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.N(this,S),this.jR=S.element),S=X.end-X.start,(D=g.tm(this.A))&&this.Nt.push(new O4(X.start,S,0,X.id,D)),this.Nt.push(new O4(X.start,S,0,X.id,H[0]),new O4(X.start,S,0,X.id,this.jR,!0),new O4(X.start,S,0,X.id,H[1],!0)),this.player.ey(this.Nt),this.hL.zr());!this.N||this.gg||RW(this)||(this.O.G("enable_player_captions_persistence_state_machine")?VO(this,!0):g.TG(this.O)?Sq(this,!0):r8(this,!0),this.C&&(this.C.Y=this.A),this.player.NU());this.N=!1}}onCueRangeEnter(R){this.rg.push(R);
th(this.SR)}onCueRangeExit(R){g.iJ(this.rg,R);this.V instanceof Mvy&&this.V.W&&this.player.zD([R]);th(this.SR)}getCaptionWindowContainerId(){return this.J.element.id}nf(){kUU(this,this.Nt);this.Nt=null}lK(){if(!this.ww||!this.Y){this.SR.stop();g.Ow(this.RB);this.rg.sort(g.LH);var R=this.rg;if(this.K){let H=g.w_(R,function(h){return this.K.indexOf(h)===-1},this);
H.length&&(R=H)}for(let H of R)H instanceof IY?pRC(this,H):$UW(this,H);for(let [H,h]of Object.entries(this.Pd)){let V=H,S=h;this.RB[V]?(S.element.parentNode||(S instanceof jEC||S instanceof YtQ||g.MF(this.Pd,(r,k)=>{k!==V&&r.L.params.Su===S.L.params.Su&&r.L.params.FD===S.L.params.FD&&r.L.params.ER===S.L.params.ER&&(r.dispose(),delete this.Pd[k]);return k===V},this),this.J.element.appendChild(S.element)),S.K(this.RB[V])):(S.dispose(),delete this.Pd[V])}}}f1(){U4(this,{},!0);
g.V9(this.player,"captionssettingschanged")}SP(){var R=this.O.G("enable_player_captions_new_style_defaults")?StW:r2S,H=R.Ym;R={background:H.background,backgroundOpacity:H.backgroundOpacity,charEdgeStyle:H.charEdgeStyle,color:H.color,fontFamily:H.fontFamily,fontSizeIncrement:H.fontSizeIncrement,fontStyle:H.bold&&H.italic?3:H.bold?1:H.italic?2:0,textOpacity:H.textOpacity,windowColor:R.windowColor,windowOpacity:R.windowOpacity};H=Fq()||{};H.background!=null&&(R.background=H.background);H.backgroundOverride!=
null&&(R.backgroundOverride=H.backgroundOverride);H.backgroundOpacity!=null&&(R.backgroundOpacity=H.backgroundOpacity);H.backgroundOpacityOverride!=null&&(R.backgroundOpacityOverride=H.backgroundOpacityOverride);H.charEdgeStyle!=null&&(R.charEdgeStyle=H.charEdgeStyle);H.charEdgeStyleOverride!=null&&(R.charEdgeStyleOverride=H.charEdgeStyleOverride);H.color!=null&&(R.color=H.color);H.colorOverride!=null&&(R.colorOverride=H.colorOverride);H.fontFamily!=null&&(R.fontFamily=H.fontFamily);H.fontFamilyOverride!=
null&&(R.fontFamilyOverride=H.fontFamilyOverride);H.fontSizeIncrement!=null&&(R.fontSizeIncrement=H.fontSizeIncrement);H.fontSizeIncrementOverride!=null&&(R.fontSizeIncrementOverride=H.fontSizeIncrementOverride);H.fontStyle!=null&&(R.fontStyle=H.fontStyle);H.fontStyleOverride!=null&&(R.fontStyleOverride=H.fontStyleOverride);H.textOpacity!=null&&(R.textOpacity=H.textOpacity);H.textOpacityOverride!=null&&(R.textOpacityOverride=H.textOpacityOverride);H.windowColor!=null&&(R.windowColor=H.windowColor);
H.windowColorOverride!=null&&(R.windowColorOverride=H.windowColorOverride);H.windowOpacity!=null&&(R.windowOpacity=H.windowOpacity);H.windowOpacityOverride!=null&&(R.windowOpacityOverride=H.windowOpacityOverride);return R}PL(R,H){var h={};Object.assign(h,Fq());Object.assign(h,R);U4(this,h,H);g.V9(this.player,"captionssettingschanged")}Uh(){!this.Y&&this.loaded&&(g.JJ(this.Pd,function(R,H){R.dispose();delete this.Pd[H]},this),this.lK())}MV(R,H){switch(R){case "fontSize":if(isNaN(H))break;
R=g.Y6(H,-2,4);this.PL({fontSizeIncrement:R});return R;case "reload":H&&!this.Y&&uj(this,this.A,!0);break;case "stickyLoading":H!==void 0&&this.O.J&&(this.O.G("enable_player_captions_persistence_state_machine")?VO(this,!(!H||!H.userInitiated)):g.TG(this.O)?Sq(this,!!H):r8(this,!!H));break;case "track":return GUJ(this,H);case "tracklist":return this.V?g.O7(this.V.V.V(!(!H||!H.includeAsr)),h=>aY(h)):[];
case "translationLanguages":return this.V?this.V.C.map(h=>Object.assign({},h)):[];
case "sampleSubtitles":this.Y||H===void 0||vG(this,!!H);break;case "sampleSubtitlesCustomized":this.Y||vG(this,!!H,H);break;case "recommendedTranslationLanguages":return g.Sz();case "defaultTranslationSourceTrackIndices":return this.V?this.V.Pd:[]}}getOptions(){var R="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.O.J&&R.push("stickyLoading");return R}Rz(){var R=this.A;if(this.j.e4("captions")){if(this.O.G("html5_modify_caption_vss_logging"))return(R=this.videoData.Wh??
null)?{cc:g.Ms(R)}:{};if(R){let H=R.vssId;R.translationLanguage&&H&&(H=`t${H}.${g.aO(R)}`);return{cc:H}}}return{}}Nf(R){this.isSubtitlesOn()?(this.O.G("enable_player_captions_persistence_state_machine")&&R?VO(this,!1):g.TG(this.O)?Sq(this,!1):r8(this,!1),kz(this),uj(this,null,!0)):this.OA(R)}OA(R){var H=RW(this)||!this.A?hT(this,!0):this.A;H&&this.TY(H.vssId,"m");this.isSubtitlesOn()||uj(this,H,this.O.G("enable_player_captions_persistence_state_machine")?R:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.A&&!RW(this)}uK(){var R=RW(this);y8(this,R)?uj(this,this.getAudioTrack().V,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),T0p(this)&&(this.N=!1,this.A=null,this.V&&(this.V.dispose(),this.V=null)),this.hM()&&(R?uj(this,hT(this,!1),!1):this.load()))}VZ(R){if(this.O.experiments.dg("web_enable_captions_set_target_container")&&R!==this.DD){var H=this.J.element;H.parentNode&&g.KK(H);(this.DD=R)?(this.DD.appendChild(H),H.style.position="absolute",H.style.bottom="0",H.style.left=
"0",H.style.width="100%",H.style.height="auto",H.style.top="auto"):(g.ab(this.player,H,4),H.style.position="absolute",H.style.bottom="auto",H.style.left="0",H.style.width="100%",H.style.height="100%",H.style.top="0");this.Uh()}}hT(R){R&&(this.W={top:R.top,right:R.right,bottom:R.bottom,left:R.left,width:1-R.left-R.right,height:1-R.top-R.bottom},this.J.element.style.top=`${this.W.top*100}%`,this.J.element.style.left=`${this.W.left*100}%`,this.J.element.style.width=`${this.W.width*100}%`,this.J.element.style.height=
`${this.W.height*100}%`,this.J.element.style.position="absolute",R=mUj(this))&&(this.J.element.style.width=`${R.width}px`,this.J.element.style.height=`${R.height}px`)}onVideoDataChange(R,H){R==="newdata"&&(this.videoData=H,this.loaded&&this.unload(),this.N=!1,this.A=null,this.V&&(this.V.dispose(),this.V=null,g.V9(this.player,"captionschanged",{})),this.hM()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}O1(){var R=this.j.Hg();R&&!R.YJ()&&R.C();this.j.isFullscreen()?(this.Y=this.Eh=
!0,this.loaded&&this.hE()):(this.Eh=this.O.controlsType==="3",this.Y=VvC(this));uj(this,this.A)}kJ(){var R=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;R&&g.h0(this.player,"innertubeCommand",R)}hJ(R,H,h){var V=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,S="";R&&(S=R.vssId,S=S.replace(V,""));var r="";R&&R.getId()&&(r=R.getId()||"");R&&R.getXtags()&&(R=R.getXtags(),R=R.replace(V,""),r=r.concat(`;${R}`));this.L==="HLS"&&(r="");this.j.hJ(H?S:"",H?r:"",h)}TY(R,
H){R=(R||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");R.length>0&&this.j.TY(R,H)}});})(_yt_player);
